### ISSUE TITLE
Access to the CheXphoto Version 1.1 Dataset

### ISSUE THREAD

**Issue by danielshawellis** [maxium0526/ptrn#1]
@maxium0526  Thank you so much for sharing this code and for you and your colleagues' work on this research. I'm currently building a mobile application to help clinicians in low-resource settings with chest x-ray interpretation, and your research has been extremely helpful.

Your paper mentions using the CheXphoto-v1.1 dataset, and I've spent a number of hours trying to figure out how to access this version of the dataset. I found the download form for CheXphoto version 1.0 here: https://stanfordmlgroup.github.io/competitions/chexphoto/ but I've not been able to find access to CheXphoto version 1.1 anywhere online. This is a problem because CheXphoto version 1.0 is structured differently and doesn't contain any images of x-ray films.

How did you get access to the CheXphoto-v1.1 dataset for this research?

**Comment by maxium0526** [comment]
You can check out this link: http://download.cs.stanford.edu/deep/CheXphoto-valid-v1.1.zip.
And make sure you read and agree with the dataset license: https://stanfordaimi.azurewebsites.net/datasets/f1577fbd-6f5c-417e-be81-850939f90daa
